name: newletter_every_14th_day

on:
  schedule:
    - cron: "*/5 * * * *"

  repository_dispatch:
    types: manual-trigger

jobs:
  newsletter:
    name: newsletter
    runs-on: ubuntu-latest

    steps:
      - name: set
        id: var
        run: |
          echo "::set-output name=SINCE::$(date --date='7 days ago' +%Y-%m-%d)"
          echo "::set-output name=UNTIL::$(date +'%Y-%m-%d')"
          echo "::set-output name=TITLE::TF-KR 주간 뉴스레터"  
          
      - name: print
        run: echo "${{ steps.var.outputs.SINCE }} . ${{ steps.var.outputs.UNTIL }} . ${{ steps.var.outputs.TITLE }}"
