name: newletter_every_14th_day

on:
  schedule:
    - cron: "*/5 * * * *"

  repository_dispatch:
    types: manual-trigger

jobs:
  newsletter:
    name: newsletter
    runs-on: ubuntu-latest

    steps:
      - name: set
        id: var
        run: |
          echo "::set-output name=one::안녕하세요?"
          echo "::set-output name=two::뉘신지..."
          echo "::set-output name=three::너 뭐냥" 
          
      - name: print
        run: echo "${{ steps.var.outputs.one }} . ${{ steps.var.outputs.two }} . ${{ steps.var.outputs.three }}"
